### ISSUE TITLE
nar fails on missing optional dependency

### ISSUE THREAD

**Issue by fred-o** [h2non/nar#130]
I have a project that uses `chokidar`, which has `fsevents` as an optional OSX-only dependency. When running nar on a linux box, it fails with the error message

```
Error: Cannot find module 'fsevents' from '/home/fredrik/slangen/node_modules/chokidar'
  at /usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:46:17
  at process (/usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:173:43)
  at ondir (/usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:188:17)
  at load (/usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:69:43)
  at onex (/usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:92:31)
  at /usr/local/lib/node_modules/artie/node_modules/nar/node_modules/resolve-tree/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```

I suspect this is a problem with `resolve-tree` (or possibly even `resolve`) rather than `nar`, but I'm reporting it here anyway :)

**Comment by h2non** [comment]
Optional dependencies should not break the build. I'll change that behavior.

**Comment by h2non** [comment]
`nar` should provide to `resolve-tree` the `optionalDependencies` lookup, but it doesn't. 
I've to introduce an improvements also in `resolve-tree` in order to determine if the package is an optional dependency and in that case don't failure in resolution error.

Will do probably tonight.

**Comment by h2non** [comment]
And thank you for reporting this.

**Comment by fred-o** [comment]
Thank you for the prompt response :) Will you also update the dependency for `resolve-tree`? The mechanism you introduced for resolutions solves an urgent problem for us.

**Comment by h2non** [comment]
Will do not, no problem.

**Comment by h2non** [comment]
Done: https://www.npmjs.com/package/resolve-tree

**Comment by h2non** [comment]
I'm sorry for the delay. Optional dependencies are now properly handled by `nar`. 
I've to support the new feature in both `resolve-tree` and `nar` packages.

The feature is shipped in `nar@0.3.35`. Feel free to update it.

**Comment by micheasherman-minted** [comment]
I'm still having the same problem with nar@0.3.35

npm install works fine, but nar create does not not. as it complains about darwin dependancies not being available on linux.

This is hitting chokidar in babble.

**Comment by h2non** [comment]
If you provide a sample package.json I could help you. Create an issue if you want.

**Comment by h2non** [comment]
@micheasherman-minted FYI: a fix introduced in `nar@0.3.36` solves the issue. Feel free to update.
